import React from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight } from 'lucide-react';
import './index.css';

const media = 'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/';
const dashboard = './terminal.html';
function LogoIcon(){return <svg className="w-7 h-7" viewBox="0 0 256 256" aria-hidden="true"><path fill="currentColor" d="M 128.005 191.173 C 128.448 156.208 156.93 128 192 128 L 192 64 L 128 64 C 128 99.346 99.346 128 64 128 L 64 192 L 128 192 Z M 192 256 L 64 256 C 28.654 256 0 227.346 0 192 L 0 64 L 64 64 L 64 0 L 192 0 C 227.346 0 256 28.654 256 64 L 256 192 L 192 192 Z"/></svg>}
function Pill({children,href=dashboard}:{children:React.ReactNode;href?:string}){return <a href={href} className="inline-flex items-center gap-3 bg-black text-white text-base font-medium pl-8 pr-2 py-2 rounded-full hover:bg-gray-800 transition-colors duration-200">{children}<span className="bg-white rounded-full p-2"><ArrowRight className="w-5 h-5 text-black" aria-hidden="true"/></span></a>}
type Brand = [string,string,number,string,number,boolean?];
const brands:Brand[]=[['NVIDIA','Georgia, serif',700,'-.02em',15],['MICROSOFT','Arial, sans-serif',900,'.08em',13],['Apple','Trebuchet MS, sans-serif',600,'.01em',15,true],['AMAZON','Courier New, monospace',700,'.12em',13],['Alphabet','Palatino, Book Antiqua, serif',400,'-.01em',16],['Meta','Impact, Arial Narrow, sans-serif',400,'.04em',14],['AMD','Verdana, sans-serif',700,'-.03em',13]];
const sources:Brand[]=[['Yahoo Finance','Georgia, serif',600,'-.02em',17],['ALPACA IEX','Arial, sans-serif',600,'.08em',15],['Alpha Vantage','Helvetica, sans-serif',600,'-.01em',16],['FINBERT','Courier New, monospace',600,'.12em',15]];
function Marquee({items,backed=false}:{items:Brand[];backed?:boolean}){return <div className="overflow-hidden"><div className={backed?'backers-track':'marquee-track'}>{[0,1].map(copy=><div key={copy} className="flex items-center" aria-hidden={copy===1?true:undefined}>{items.map(([name,fontFamily,fontWeight,letterSpacing,fontSize,italic])=><span key={name} className={`${backed?'mx-10 text-black/50':'mx-7 text-black/60'} shrink-0 whitespace-nowrap`} style={{fontFamily,fontWeight,letterSpacing,fontSize,fontStyle:italic?'italic':undefined}}>{name}</span>)}</div>)}</div></div>}
const links=[['Platform','#platform'],['Features','#features'],['Data','#data'],['Research','#research']];
function App(){return <main className="flex flex-col bg-[#F5F5F5] text-black">
  <div className="relative h-screen min-h-[620px] flex flex-col overflow-hidden">
    <nav className="absolute top-0 left-0 right-0 z-20 px-6 py-5" aria-label="Main navigation"><div className="max-w-[88rem] mx-auto flex items-center justify-between gap-2 sm:gap-4"><a href="/" className="flex items-center gap-2 text-lg sm:text-2xl font-medium tracking-tight whitespace-nowrap" aria-label="MarketPulse home"><LogoIcon/>MarketPulse</a><div className="hidden md:flex gap-8">{links.map(([label,href])=><a key={label} href={href} className="text-base text-gray-700 hover:text-black font-medium transition-colors duration-200">{label}</a>)}</div><a href={dashboard} className="bg-black text-white text-xs sm:text-base font-medium px-3 sm:px-7 py-2.5 rounded-full whitespace-nowrap hover:bg-gray-800 transition-colors duration-200" title="Open the MarketPulse dashboard">Open dashboard</a><details className="md:hidden relative"><summary className="cursor-pointer text-sm">Menu</summary><div className="absolute right-0 top-9 rounded-xl bg-white p-5 shadow-lg flex flex-col gap-4">{links.map(([label,href])=><a key={label} href={href}>{label}</a>)}</div></details></div></nav>
    <section className="flex-1 px-6 pt-20 pb-6 flex items-end"><div className="hero-card relative w-full rounded-2xl overflow-hidden"><video autoPlay muted loop playsInline aria-hidden="true" className="absolute inset-0 w-full h-full object-cover" src={media+'hf_20260423_161253_c72b1869-400f-45ed-ac0c-52f68c2ed5bd.mp4'}/><div className="hero-copy relative z-10 flex flex-col items-start justify-start h-full p-12 pt-36 max-w-[88rem] mx-auto"><h1 className="text-5xl md:text-6xl font-medium leading-tight max-w-xl mb-4 tracking-[-0.04em]">Market moves.<br/>In context.</h1><p className="text-black/70 text-base md:text-lg max-w-md mb-8 leading-relaxed" style={{fontFamily:"'Inter', ui-sans-serif, system-ui, sans-serif"}}>Explore 20 technology equities through price charts, financial news and AI sentiment. Bring the evidence behind each market move into view.</p><Pill>Explore the dashboard</Pill><div className="hero-marquee mt-24 w-full max-w-md"><Marquee items={brands}/></div></div></div></section>
  </div>
  <section id="platform" className="px-6 py-24"><div className="max-w-[88rem] mx-auto"><div className="grid grid-cols-1 md:grid-cols-2 gap-12 mb-16 items-start"><div><h2 className="text-4xl md:text-5xl font-medium leading-tight mb-8 tracking-[-0.03em]">Meet MarketPulse.</h2><Pill href="#features">Explore the features</Pill></div><p className="text-black/70 text-2xl md:text-3xl leading-relaxed">One research workspace for technology stocks. Connect price action with company news, momentum signals and historical risk.</p></div><div id="features" className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><article className="lg:col-span-2 rounded-2xl bg-cover bg-center bg-[#dfdfcf] p-7 min-h-80 flex flex-col justify-between" style={{backgroundImage:`url("https://images.higgs.ai/?default=1&output=webp&url=${encodeURIComponent(media+'hf_20260423_164207_f243351d-ed59-48ec-83a0-a5e996bdbe3c.png')}&w=1280&q=85")`}}><h3 className="text-2xl font-medium leading-snug tracking-[-0.02em]">The story behind the chart</h3><p className="text-black/70 text-base max-w-xs">Follow company headlines with FinBERT sentiment, relevance scores and model confidence alongside historical price action.</p></article>{[['Market signals,\nmade visible.','Explore candlestick charts, a daily return heatmap and rule-based momentum signals across 20 technology equities.'],['Risk, with\nperspective.','Inspect volatility, RSI and MACD, then compare historical strategy returns and drawdowns for each company.']].map(([title,body])=><article key={title} className="bg-[#2B2644] rounded-2xl p-7 min-h-80 flex flex-col justify-between text-white"><h3 className="text-2xl font-medium whitespace-pre-line tracking-[-0.02em]">{title}</h3><p className="text-white/60 text-base">{body}</p></article>)}</div></div></section>
  <section id="data" className="px-6"><div className="max-w-[88rem] mx-auto grid grid-cols-1 md:grid-cols-4 gap-8 items-center"><p className="text-black/70 text-base leading-relaxed">Market data and news sources.<br/>Financial language analysis.</p><div className="md:col-span-3 min-w-0"><Marquee items={sources} backed/></div></div></section>
  <section id="research" className="px-6 py-24"><div className="max-w-[88rem] mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 items-start"><div className="md:pr-12 md:pt-2"><p className="text-black/60 text-sm mb-2">Inside the Research Lab</p><h2 className="text-5xl md:text-6xl font-medium leading-none mb-6 tracking-[-0.04em]">Follow the evidence</h2><p className="text-black/60 text-base leading-relaxed max-w-sm">Start with a company. Compare momentum and sentiment-based strategies, explore news-event responses and examine historical risk across years.</p></div><article className="commerce-card relative rounded-3xl overflow-hidden min-h-[720px]"><video autoPlay muted loop playsInline aria-hidden="true" preload="metadata" className="object-cover absolute inset-0 w-full h-full" src={media+'hf_20260423_183428_ab5e672a-f608-4dcb-b319-f3e040f02e2d.mp4'}/><div className="relative z-10 p-10 md:p-12"><h3 className="text-4xl md:text-5xl font-medium leading-tight mb-5 tracking-[-0.03em]">From headline<br/>to hypothesis.</h3><p className="text-black/70 text-base max-w-md mb-8">Compare annual strategy returns, maximum drawdowns and company news-event studies in one place. Review data coverage and statistical evidence before drawing conclusions.</p><a href={dashboard} className="inline-flex items-center gap-3 group"><span className="w-9 h-9 rounded-full bg-white/80 backdrop-blur flex items-center justify-center group-hover:bg-white transition-colors duration-200"><ArrowRight className="w-4 h-4" aria-hidden="true"/></span>Start researching</a></div></article></div></section>
<footer className="px-6 pb-8 text-sm text-black/60"><div className="max-w-[88rem] mx-auto flex flex-col sm:flex-row justify-between gap-3"><span>MarketPulse · Technology equity research</span><span>Historical analysis, not a forecast. Live IEX data when available.</span></div></footer>
</main>}
createRoot(document.getElementById('root')!).render(<App/>);
